services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.11
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_PLUGINS=rabbitmq_management
    volumes:
      - rabbitmq-data:/bitnami
    healthcheck:
      test: rabbitmq-diagnostics -q status && rabbitmq-diagnostics -q check_local_alarms
      interval: 15s
      timeout: 20s
      start_period: 15s
      retries: 3
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    ports:
      - '27017-27019:27017-27019'
    environment:
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=auth
    volumes:
      - mongodb-data:/bitnami/mongodb
    healthcheck:
      test: >
        if mongo --quiet mongodb/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'; then
          exit 0
        fi
      interval: 15s
      timeout: 20s
      retries: 3
      start_period: 15s
volumes:
  rabbitmq-data:
    driver: local
  mongodb-data:
    driver: local
